{{- if or .Values.nodeExporter.enabled .Values.nodeExporter.existingRelease }}
apiVersion: {{ printf "%s/v1" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-node-exporter
  labels:
    app: {{ template "prometheus-operator.name" . }}-node-exporter
{{ include "prometheus-operator.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Values.nodeExporter.jobLabel }}
  {{- if .Values.nodeExporter.existingRelease }}
  namespaceSelector:
    matchNames:
    - {{ .Values.nodeExporter.existingRelease.namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- if .Values.nodeExporter.existingRelease }}
{{ toYaml .Values.nodeExporter.existingRelease.labels | indent 6 }}
      {{- else }}
      app: prometheus-node-exporter
      release: {{ .Release.Name }}
      {{- end }}
  endpoints:
  - port: metrics
    {{- if .Values.nodeExporter.serviceMonitor.interval }}
    interval: {{ .Values.nodeExporter.serviceMonitor.interval }}
    {{- end }}
{{- if .Values.nodeExporter.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.nodeExporter.serviceMonitor.metricRelabelings | indent 4 }}
{{- end }}
{{- end }}
