{{- if or .Values.kubeStateMetrics.enabled .Values.kubeStateMetrics.existingRelease }}
apiVersion: {{ printf "%s/v1" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-state-metrics
  labels:
    app: {{ template "prometheus-operator.name" . }}-kube-state-metrics
{{ include "prometheus-operator.labels" . | indent 4 }}
spec:
  jobLabel: app
  endpoints:
  - port: http
    {{- if .Values.kubeStateMetrics.serviceMonitor.interval }}
    interval: {{ .Values.kubeStateMetrics.serviceMonitor.interval }}
    {{- end }}
    honorLabels: true
{{- if .Values.kubeStateMetrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.kubeStateMetrics.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
  {{- if .Values.kubeStateMetrics.existingRelease }}
  namespaceSelector:
    matchNames:
    - {{ .Values.kubeStateMetrics.existingRelease.namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- if .Values.kubeStateMetrics.existingRelease }}
{{ toYaml .Values.kubeStateMetrics.existingRelease.labels | indent 6 }}
      {{- else }}
      app: kube-state-metrics
      release: "{{ .Release.Name }}"
      {{- end }}
{{- end }}
